export const GET_ANTIBIOTICS = "GET_ANTIBIOTICS";
export const ADD_ANTIBIOTIC = "ADD_ANTIBIOTIC";
export const DELETE_ANTIBIOTIC = "DELETE_ANTIBIOTIC";
export const ANTIBIOTICS_LOADING = "ANTIBIOTICS_LOADING";

export const GET_ANTIBIOTIC_TYPES = "GET_ANTIBIOTIC_TYPES";
export const ADD_ANTIBIOTIC_TYPE = "ADD_ANTIBIOTIC_TYPE";
export const DELETE_ANTIBIOTIC_TYPE = "DELETE_ANTIBIOTIC_TYPE";
export const ANTIBIOTIC_TYPES_LOADING = "ANTIBIOTIC_TYPES_LOADING";

export const SWITCH_LOCALE = "SWITCH_LOCALE";
