export const GET_ANTIBIOTICS = "GET_ANTIBIOTICS";
export const ADD_ANTIBIOTIC = "ADD_ANTIBIOTIC";
export const DELETE_ANTIBIOTIC = "DELETE_ANTIBIOTIC";
export const ANTIBIOTICS_LOADING = "ANTIBIOTICS_LOADING";
